### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [lambtron/ama#3]

**Comment by lambtron** [comment]
My parents were both software engineers. My first introduction to programming was [Logo](https://en.wikipedia.org/wiki/Logo_%28programming_language%29) in elementary school. But what _really_ got me hooked was programming ASCII games for my ti-83+ calculator in middle school.

These games were written in BASIC. I looked at how other games worked and started tweaking them. Then, I started writing them completely from scratch. What I found most gratifying was sharing these games with my friends, who enjoyed (hopefully) playing them!
