### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [lambtron/ama#6]

**Comment by lambtron** [comment]
I really like these:

![](http://ak-hdl.buzzfed.com/static/enhanced/webdr06/2013/8/26/10/anigif_enhanced-buzz-15213-1377527073-0.gif)

They're from a japanese horse racing game. More info [here](http://www.buzzfeed.com/mrloganrhoades/japanese-horse-racing-video-game-is-the-weirdest-thing-in-th#.wg6pVy9a7).
